#!/bin/bash
#
# task-queue	Start up Task Queue job logger
#
# chkconfig: 2345 95 05
# description: Log status of task queue jobs.

set -e
set -u

HOST=$(hostname -s)
if [[ $HOST =~ ^d ]]; then
	ENV=dev
else
	ENV=prod
fi

MY_CNF=/content/$ENV/rstar/etc/my-taskqueue.cnf

if [ ! -f "$MY_CNF" ]; then
	echo "MySQL confile '$MY_CNF' doesn't exist." 1>&2
	exit 1
fi

# Clear environment and read values from config file. We don't
# unset FOREGROUND because we set this in systemd service file
unset TQHOME TQUSER LOGDIR MQHOST RVM_RUBY_VERSION

CONFIG_FILE=/content/$ENV/rstar/etc/task-queue.sysconfig

if [ -f "$CONFIG_FILE" ]; then
	# shellcheck disable=SC1090
	. "$CONFIG_FILE"
fi

TQHOME=${TQHOME:-/usr/local/dlib/task-queue}

TQUSER=${TQUSER:-rstar}

LOGDIR=${LOGDIR:-/content/$ENV/rstar/tmp/mdi/task-queue/logs}

MQHOST=${MQHOST:-localhost}

FOREGROUND=${FOREGROUND:-false}

RVM_RUBY_VERSION=${RVM_RUBY_VERSION:-}

RVM_GEM_DIR="/usr/share/rvm/gems"

RETVAL=0

get_pid() {
	pgrep -f 'ruby.*log-job-status.rb' || true
}

print_cmd() {
	local cmd_str

	printf -v cmd_str '%q ' "$@"
	cmd_str="${cmd_str% }"

	echo "cmd: $cmd_str" 1>&2
}

start() {
	PID=$(get_pid)
	if [ -n "$PID" ]; then
		echo "log-job-status already running with pid '$PID'" 1>&2
		exit 1
	fi
	LOGFILE=$LOGDIR/$HOST/log-job-status.$HOST.log
	CMD=()
	if [ -n "$RVM_RUBY_VERSION" ]; then
		CMD+=("$RVM_GEM_DIR/ruby-$RVM_RUBY_VERSION@task-queue/wrappers/ruby")
	fi
	CMD+=("$TQHOME/log-job-status.rb" -m "$MQHOST" -c "$MY_CNF" -l "$LOGFILE")
	if [ "$FOREGROUND" != "true" ]; then
		CMD+=(-d)
	fi
	print_cmd "${CMD[@]}"
	if [ "$TQUSER" = "$(whoami)" ]; then
		exec "${CMD[@]}"
	else
		if [ -f "$LOGFILE" ]; then
			TQGROUP=$(id -gn "$TQUSER")
			chown "$TQUSER:$TQGROUP" "$LOGFILE"
		fi
		su -ls /bin/bash "$TQUSER" -c 'exec "$@"' -- _ "${CMD[@]}"
	fi
	RETVAL=$?
}

stop() {
	PID=$(get_pid)
	[ -n "$PID" ] && kill "$PID" 2>/dev/null
	RETVAL=$?
}

restart() {
	stop
	start
}


case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}" >&2
		exit 3
		;;
esac

exit $RETVAL
