---
services:
  - audio:transcode
  - bagit:validate
  - book_publisher:create_derivatives
  - book_publisher:create_map
  - book_publisher:create_ocr
  - book_publisher:create_pdf
  - book_publisher:gen_all
  - book_publisher:stitch_pages
  - util:env
  - util:fortune
  - util:nope
  - util:ping
  - video:transcode
