#!/bin/sh

PIDFILE=taskqueueserver.pid

MQHOST=${MQHOST:-localhost}

start() {
	./workers.rb -m $MQHOST
}

stop() {
	[ -f $PIDFILE ] && kill `cat $PIDFILE`
}

restart() {
	stop
	sleep 5
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|force-reload|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 3
	;;
esac

:
