#!/bin/bash

exec 2>&1
# set -x
set -e

PIDFILE=taskqueueserver.pid

LOGDIR=/content/prod/rstar/tmp/mdi/task-queue/logs

MQHOST=${MQHOST:-localhost}

RVMRC=$HOME/.rvm/scripts/rvm

if [ -s $RVMRC ]; then
	. $RVMRC
fi

RETVAL=0

start() {
	HOST=$(hostname -s)
	LOGFILE=$LOGDIR/$HOST/worker.$HOST.log
	./workers.rb -m $MQHOST -l $LOGFILE
	RETVAL=$?
}

stop() {
	if [ -f $PIDFILE ]; then
		kill `cat $PIDFILE`
		RETVAL=$?
	fi
}

restart() {
	stop
	sleep 5
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|force-reload|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 3
	;;
esac

exit $RETVAL
